# Generated by Django 4.2.3 on 2025-06-15 11:38

import banking.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0002_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'Checking Account'), ('SAVINGS', 'Savings Account')], default='CHECKING', max_length=10),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Annual interest rate (%) for savings accounts', max_digits=5),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Designates whether this is the primary account for the user'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment'), ('PURCHASE', 'Purchase'), ('REFUND', 'Refund'), ('INTEREST', 'Interest'), ('FEE', 'Fee')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('user', 'account_type')},
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(default=banking.models.generate_card_number, max_length=16, unique=True)),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(default=banking.models.generate_cvv, max_length=3)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('available_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apr', models.DecimalField(decimal_places=2, help_text='Annual Percentage Rate (%)', max_digits=5)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.creditcard'),
        ),
    ]
